name: 🚀 Java API CI/CD Pipeline (GCP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: "java-api:${{ github.sha }}"
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  REGISTRY_IMAGE: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/java-api:${{ github.sha }}"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Checkout Code
        uses: actions/checkout@v3

      - name: ☕ Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 📦 Build with Maven
        run: mvn clean package -DskipTests

      - name: 🧪 Run Tests
        run: mvn test

      - name: 🛠 Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: 🔐 Trivy Scan (Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: table
          exit-code: 0
          severity: HIGH,CRITICAL

      # 🔐 LOGIN GCP
      - name: 🔐 Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: 🔐 Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: 🏷️ Tag Docker Image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY_IMAGE }}

      - name: 📤 Push to Artifact Registry
        run: docker push ${{ env.REGISTRY_IMAGE }}